version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wog_score_flask:${DOCKER_IMAGE_TAG}
    container_name: wog_score_flask
    ports:
      - "8777:5000"
